// https://gist.github.com/timraay/5634d85eab552b5dfafb9fd61273dc52#available-maps

export const maps = [
  {
    mapName: "CAR_S_1944_Day_P_Skirmish",
    queryName: "DEV_F_DAY_SKM",
    prettyName: "CARENTAN Skirmish",
    base: "Carentan",
    gamemode: "Skirmish",
    environment: "Day",
    attackers: "",
    image: "Carentan",
  },
  {
    mapName: "CAR_S_1944_Dusk_P_Skirmish",
    queryName: "DEV_F_DUSK_SKM",
    prettyName: "CARENTAN Skirmish",
    base: "Carentan",
    gamemode: "Skirmish",
    environment: "Dusk",
    attackers: "",
    image: "Carentan",
  },
  {
    mapName: "CAR_S_1944_Rain_P_Skirmish",
    queryName: "DEV_F_RAIN_SKM",
    prettyName: "CARENTAN Skirmish",
    base: "Carentan",
    gamemode: "Skirmish",
    environment: "Rain",
    attackers: "",
    image: "Carentan",
  },
  {
    mapName: "carentan_offensive_ger",
    queryName: "CT",
    prettyName: "CARENTAN Offensive",
    base: "Carentan",
    gamemode: "Offensive",
    environment: "Day",
    attackers: "GER",
    image: "Carentan",
  },
  {
    mapName: "carentan_offensive_us",
    queryName: "CT",
    prettyName: "CARENTAN Offensive",
    base: "Carentan",
    gamemode: "Offensive",
    environment: "Day",
    attackers: "US",
    image: "Carentan",
  },
  {
    mapName: "carentan_warfare",
    queryName: "CT",
    prettyName: "CARENTAN Warfare",
    base: "Carentan",
    gamemode: "Warfare",
    environment: "Day",
    attackers: "",
    image: "Carentan",
  },
  {
    mapName: "carentan_warfare_night",
    queryName: "CT_N",
    prettyName: "CARENTAN NIGHT Warfare",
    base: "Carentan",
    gamemode: "Warfare",
    environment: "Night",
    attackers: "",
    image: "Carentan",
  },
  {
    mapName: "driel_offensive_ger",
    queryName: "Driel_Day",
    prettyName: "DRIEL Offensive",
    base: "Driel",
    gamemode: "Offensive",
    environment: "Day",
    attackers: "GER",
    image: "Driel",
  },
  {
    mapName: "driel_offensive_us",
    queryName: "Driel_Day",
    prettyName: "DRIEL Offensive",
    base: "Driel",
    gamemode: "Offensive",
    environment: "Day",
    attackers: "GB",
    image: "Driel",
  },
  {
    mapName: "driel_warfare",
    queryName: "Driel",
    prettyName: "DRIEL Warfare",
    base: "Driel",
    gamemode: "Warfare",
    environment: "Dawn",
    attackers: "",
    image: "Driel",
  },
  {
    mapName: "driel_warfare_night",
    queryName: "Driel_N",
    prettyName: "DRIEL Warfare",
    base: "Driel",
    gamemode: "Warfare",
    environment: "Night",
    attackers: "",
    image: "Driel",
  },
  {
    mapName: "DRL_S_1944_P_Skirmish",
    queryName: "DEV_C_SKM",
    prettyName: "DRIEL Skirmish",
    base: "Driel",
    gamemode: "Skirmish",
    environment: "Dawn",
    attackers: "",
    image: "Driel",
  },
  {
    mapName: "DRL_S_1944_Day_P_Skirmish",
    queryName: "DEV_C_Day_SKM",
    prettyName: "DRIEL Skirmish",
    base: "Driel",
    gamemode: "Skirmish",
    environment: "Day",
    attackers: "",
    image: "Driel",
  },
  {
    mapName: "DRL_S_1944_Night_P_Skirmish",
    queryName: "DEV_C_Night_SKM",
    prettyName: "DRIEL Skirmish",
    base: "Driel",
    gamemode: "Skirmish",
    environment: "Night",
    attackers: "",
    image: "Driel",
  },
  {
    mapName: "ELA_S_1942_P_Skirmish",
    queryName: "DEV_D_Day_SKM",
    prettyName: "EL ALAMEIN Skirmish",
    base: "El Alamein",
    gamemode: "Skirmish",
    environment: "Day",
    attackers: "",
    image: "El-alamein",
  },
  {
    mapName: "ELA_S_1942_Night_P_Skirmish",
    queryName: "DEV_D_Night_SKM",
    prettyName: "EL ALAMEIN Skirmish",
    base: "El Alamein",
    gamemode: "Skirmish",
    environment: "Dusk",
    attackers: "",
    image: "El-alamein",
  },
  {
    mapName: "elalamein_offensive_CW",
    queryName: "elalamein",
    prettyName: "EL ALAMEIN Offensive",
    base: "El Alamein",
    gamemode: "Offensive",
    environment: "Day",
    attackers: "GB",
    image: "El-alamein",
  },
  {
    mapName: "elalamein_offensive_ger",
    queryName: "elalamein",
    prettyName: "EL ALAMEIN Offensive",
    base: "El Alamein",
    gamemode: "Offensive",
    environment: "Day",
    attackers: "GER",
    image: "El-alamein",
  },
  {
    mapName: "elalamein_warfare",
    queryName: "elalamein",
    prettyName: "EL ALAMEIN Warfare",
    base: "El Alamein",
    gamemode: "Warfare",
    environment: "Day",
    attackers: "",
    image: "El-alamein",
  },
  {
    mapName: "elalamein_warfare_night",
    queryName: "elalamein_N",
    prettyName: "EL ALAMEIN Warfare",
    base: "El Alamein",
    gamemode: "Warfare",
    environment: "Dusk",
    attackers: "",
    image: "El-alamein",
  },
  {
    mapName: "elsenbornridge_offensiveger_day",
    queryName: "DEV_N",
    prettyName: "ELSENBORN RIDGE Offensive",
    base: "Elsenborn Ridge",
    gamemode: "Offensive",
    environment: "Day",
    attackers: "GER",
    image: "ElsenbornRidge",
  },
  {
    mapName: "elsenbornridge_offensiveger_morning",
    queryName: "DEV_N_Morning",
    prettyName: "ELSENBORN RIDGE Offensive",
    base: "Elsenborn Ridge",
    gamemode: "Offensive",
    environment: "Dawn",
    attackers: "GER",
    image: "ElsenbornRidge",
  },
  {
    mapName: "elsenbornridge_offensiveger_night",
    queryName: "DEV_N_Night",
    prettyName: "ELSENBORN RIDGE Offensive",
    base: "Elsenborn Ridge",
    gamemode: "Offensive",
    environment: "Night",
    attackers: "GER",
    image: "ElsenbornRidge",
  },
  {
    mapName: "elsenbornridge_offensiveUS_day",
    queryName: "DEV_N",
    prettyName: "ELSENBORN RIDGE Offensive",
    base: "Elsenborn Ridge",
    gamemode: "Offensive",
    environment: "Day",
    attackers: "US",
    image: "ElsenbornRidge",
  },
  {
    mapName: "elsenbornridge_offensiveUS_morning",
    queryName: "DEV_N_Morning",
    prettyName: "ELSENBORN RIDGE Offensive",
    base: "Elsenborn Ridge",
    gamemode: "Offensive",
    environment: "Dawn",
    attackers: "US",
    image: "ElsenbornRidge",
  },
  {
    mapName: "elsenbornridge_offensiveUS_night",
    queryName: "DEV_N_Night",
    prettyName: "ELSENBORN RIDGE Offensive",
    base: "Elsenborn Ridge",
    gamemode: "Offensive",
    environment: "Night",
    attackers: "US",
    image: "ElsenbornRidge",
  },
  {
    mapName: "elsenbornridge_skirmish_day",
    queryName: "DEV_N_Day_SKM",
    prettyName: "ELSENBORN RIDGE Skirmish",
    base: "Elsenborn Ridge",
    gamemode: "Skirmish",
    environment: "Day",
    attackers: "",
    image: "ElsenbornRidge",
  },
  {
    mapName: "elsenbornridge_skirmish_morning",
    queryName: "DEV_N_Morning_SKM",
    prettyName: "ELSENBORN RIDGE Skirmish",
    base: "Elsenborn Ridge",
    gamemode: "Skirmish",
    environment: "Dawn",
    attackers: "",
    image: "ElsenbornRidge",
  },
  {
    mapName: "elsenbornridge_skirmish_night",
    queryName: "DEV_N_Night_SKM",
    prettyName: "ELSENBORN RIDGE Skirmish",
    base: "Elsenborn Ridge",
    gamemode: "Skirmish",
    environment: "Night",
    attackers: "",
    image: "ElsenbornRidge",
  },
  {
    mapName: "elsenbornridge_warfare_day",
    queryName: "DEV_N",
    prettyName: "ELSENBORN RIDGE Warfare",
    base: "Elsenborn Ridge",
    gamemode: "Warfare",
    environment: "Day",
    attackers: "",
    image: "ElsenbornRidge",
  },
  {
    mapName: "elsenbornridge_warfare_morning",
    queryName: "DEV_N_Morning",
    prettyName: "ELSENBORN RIDGE Warfare",
    base: "Elsenborn Ridge",
    gamemode: "Warfare",
    environment: "Dawn",
    attackers: "",
    image: "ElsenbornRidge",
  },
  {
    mapName: "elsenbornridge_warfare_night",
    queryName: "DEV_N_Night",
    prettyName: "ELSENBORN RIDGE Warfare",
    base: "Elsenborn Ridge",
    gamemode: "Warfare",
    environment: "Night",
    attackers: "",
    image: "ElsenbornRidge",
  },
  {
    mapName: "foy_offensive_ger",
    queryName: "Foy",
    prettyName: "FOY Offensive",
    base: "Foy",
    gamemode: "Offensive",
    environment: "Day",
    attackers: "GER",
    image: "Foy",
  },
  {
    mapName: "foy_offensive_us",
    queryName: "Foy",
    prettyName: "FOY Offensive",
    base: "Foy",
    gamemode: "Offensive",
    environment: "Day",
    attackers: "US",
    image: "Foy",
  },
  {
    mapName: "foy_warfare",
    queryName: "Foy",
    prettyName: "FOY Warfare",
    base: "Foy",
    gamemode: "Warfare",
    environment: "Day",
    attackers: "",
    image: "Foy",
  },
  {
    mapName: "foy_warfare_night",
    queryName: "Foy_N",
    prettyName: "FOY Warfare",
    base: "Foy",
    gamemode: "Warfare",
    environment: "Night",
    attackers: "",
    image: "Foy",
  },
  {
    mapName: "HIL_S_1944_Day_P_Skirmish",
    queryName: "DEV_H_Day_Skirmish",
    prettyName: "HILL 400 Skirmish",
    base: "Hill 400",
    gamemode: "Skirmish",
    environment: "Day",
    attackers: "",
    image: "Hill-400",
  },
  {
    mapName: "HIL_S_1944_Dusk_P_Skirmish",
    queryName: "DEV_H_Dusk_Skirmish",
    prettyName: "HILL 400 Skirmish",
    base: "Hill 400",
    gamemode: "Skirmish",
    environment: "Dusk",
    attackers: "",
    image: "Hill-400",
  },
  {
    mapName: "hill400_offensive_ger",
    queryName: "Hill400",
    prettyName: "HILL 400 Offensive",
    base: "Hill 400",
    gamemode: "Offensive",
    environment: "Foggy",
    attackers: "GER",
    image: "Hill-400",
  },
  {
    mapName: "hill400_offensive_US**",
    queryName: "Hill400",
    prettyName: "HILL 400 Offensive",
    base: "Hill 400",
    gamemode: "Offensive",
    environment: "Day",
    attackers: "US",
    image: "Hill-400",
  },
  {
    mapName: "hill400_warfare",
    queryName: "Hill400",
    prettyName: "HILL 400 Warfare",
    base: "Hill 400",
    gamemode: "Warfare",
    environment: "Day",
    attackers: "",
    image: "Hill-400",
  },
  {
    mapName: "hill400_warfare_night***",
    queryName: "Hill400_N",
    prettyName: "HILL 400 Warfare",
    base: "Hill 400",
    gamemode: "Warfare",
    environment: "Night",
    attackers: "",
    image: "Hill-400",
  },
  {
    mapName: "hurtgenforest_offensive_ger",
    queryName: "Hurtgen",
    prettyName: "HÜRTGEN FOREST Offensive",
    base: "Hürtgen Forest",
    gamemode: "Offensive",
    environment: "Foggy",
    attackers: "GER",
    image: "HurtgenForest",
  },
  {
    mapName: "hurtgenforest_offensive_US",
    queryName: "Hurtgen",
    prettyName: "HÜRTGEN FOREST Offensive",
    base: "Hürtgen Forest",
    gamemode: "Offensive",
    environment: "Day",
    attackers: "US",
    image: "HurtgenForest",
  },
  {
    mapName: "hurtgenforest_warfare_V2",
    queryName: "Hurtgen",
    prettyName: "HÜRTGEN FOREST Warfare",
    base: "Hürtgen Forest",
    gamemode: "Warfare",
    environment: "Day",
    attackers: "",
    image: "HurtgenForest",
  },
  {
    mapName: "hurtgenforest_warfare_V2_night",
    queryName: "Hurtgen_N",
    prettyName: "HÜRTGEN FOREST Warfare",
    base: "Hürtgen Forest",
    gamemode: "Warfare",
    environment: "Night",
    attackers: "",
    image: "HurtgenForest",
  },
  {
    mapName: "kharkov_offensive_ger",
    queryName: "Kharkov",
    prettyName: "Kharkov Offensive",
    base: "Kharkov",
    gamemode: "Offensive",
    environment: "Day",
    attackers: "GER",
    image: "Kharkov",
  },
  {
    mapName: "kharkov_offensive_rus",
    queryName: "Kharkov",
    prettyName: "Kharkov Offensive",
    base: "Kharkov",
    gamemode: "Offensive",
    environment: "Day",
    attackers: "RUS",
    image: "Kharkov",
  },
  {
    mapName: "kharkov_warfare",
    queryName: "Kharkov",
    prettyName: "Kharkov Warfare",
    base: "Kharkov",
    gamemode: "Warfare",
    environment: "Day",
    attackers: "",
    image: "Kharkov",
  },
  {
    mapName: "kharkov_warfare_night",
    queryName: "Kharkov_N",
    prettyName: "Kharkov Warfare",
    base: "Kharkov",
    gamemode: "Warfare",
    environment: "Night",
    attackers: "",
    image: "Kharkov",
  },
  {
    mapName: "kursk_offensive_ger",
    queryName: "Kursk",
    prettyName: "KURSK Offensive",
    base: "Kursk",
    gamemode: "Offensive",
    environment: "Day",
    attackers: "GER",
    image: "Kursk",
  },
  {
    mapName: "kursk_offensive_rus",
    queryName: "Kursk",
    prettyName: "KURSK Offensive",
    base: "Kursk",
    gamemode: "Offensive",
    environment: "Day",
    attackers: "RUS",
    image: "Kursk",
  },
  {
    mapName: "kursk_warfare",
    queryName: "Kursk",
    prettyName: "KURSK Warfare",
    base: "Kursk",
    gamemode: "Warfare",
    environment: "Day",
    attackers: "",
    image: "Kursk",
  },
  {
    mapName: "kursk_warfare_night",
    queryName: "Kursk_N",
    prettyName: "KURSK Warfare",
    base: "Kursk",
    gamemode: "Warfare",
    environment: "Night",
    attackers: "",
    image: "Kursk",
  },
  {
    mapName: "mortain_offensiveger_day",
    queryName: "Mortain",
    prettyName: "MORTAIN Offensive",
    base: "Mortain",
    gamemode: "Offensive",
    environment: "Day",
    attackers: "GER",
    image: "Mortain",
  },
  {
    mapName: "mortain_offensiveger_evening",
    queryName: "Mortain_E",
    prettyName: "MORTAIN Offensive",
    base: "Mortain",
    gamemode: "Offensive",
    environment: "Dawn",
    attackers: "GER",
    image: "Mortain",
  },
  {
    mapName: "mortain_offensiveger_overcast",
    queryName: "Mortain_O",
    prettyName: "MORTAIN Offensive",
    base: "Mortain",
    gamemode: "Offensive",
    environment: "Overcast",
    attackers: "GER",
    image: "Mortain",
  },
  {
    mapName: "mortain_offensiveUS_day**",
    queryName: "Mortain",
    prettyName: "MORTAIN Offensive",
    base: "Mortain",
    gamemode: "Offensive",
    environment: "Day",
    attackers: "US",
    image: "Mortain",
  },
  {
    mapName: "mortain_offensiveUS_evening",
    queryName: "Mortain_E",
    prettyName: "MORTAIN Offensive",
    base: "Mortain",
    gamemode: "Offensive",
    environment: "Dawn",
    attackers: "US",
    image: "Mortain",
  },
  {
    mapName: "mortain_offensiveUS_overcast**",
    queryName: "Mortain_O",
    prettyName: "MORTAIN Offensive",
    base: "Mortain",
    gamemode: "Offensive",
    environment: "Overcast",
    attackers: "US",
    image: "Mortain",
  },
  {
    mapName: "mortain_skirmish_day",
    queryName: "Mortain_SKM_Day",
    prettyName: "MORTAIN Skirmish",
    base: "Mortain",
    gamemode: "Skirmish",
    environment: "Day",
    attackers: "",
    image: "Mortain",
  },
  {
    mapName: "mortain_skirmish_evening",
    queryName: "Mortain_SKM_Evening",
    prettyName: "MORTAIN Skirmish",
    base: "Mortain",
    gamemode: "Skirmish",
    environment: "Dawn",
    attackers: "",
    image: "Mortain",
  },
  {
    mapName: "mortain_skirmish_overcast",
    queryName: "Mortain_SKM_Overcast",
    prettyName: "MORTAIN Skirmish",
    base: "Mortain",
    gamemode: "Skirmish",
    environment: "Overcast",
    attackers: "",
    image: "Mortain",
  },
  {
    mapName: "mortain_warfare_day",
    queryName: "Mortain",
    prettyName: "MORTAIN Warfare",
    base: "Mortain",
    gamemode: "Warfare",
    environment: "Day",
    attackers: "",
    image: "Mortain",
  },
  {
    mapName: "mortain_warfare_evening",
    queryName: "Mortain_E",
    prettyName: "MORTAIN Warfare",
    base: "Mortain",
    gamemode: "Warfare",
    environment: "Dawn",
    attackers: "",
    image: "Mortain",
  },
  {
    mapName: "mortain_warfare_overcast",
    queryName: "Mortain_O",
    prettyName: "MORTAIN Warfare",
    base: "Mortain",
    gamemode: "Warfare",
    environment: "Overcast",
    attackers: "",
    image: "Mortain",
  },
  {
    mapName: "omahabeach_offensive_ger",
    queryName: "Omaha",
    prettyName: "OMAHA BEACH Offensive",
    base: "Omaha Beach",
    gamemode: "Offensive",
    environment: "Day",
    attackers: "GER",
    image: "OmahaBeach",
  },
  {
    mapName: "omahabeach_offensive_us",
    queryName: "Omaha",
    prettyName: "OMAHA BEACH Offensive",
    base: "Omaha Beach",
    gamemode: "Offensive",
    environment: "Day",
    attackers: "US",
    image: "OmahaBeach",
  },
  {
    mapName: "omahabeach_warfare",
    queryName: "Omaha",
    prettyName: "OMAHA BEACH Warfare",
    base: "Omaha Beach",
    gamemode: "Warfare",
    environment: "Day",
    attackers: "",
    image: "OmahaBeach",
  },
  {
    mapName: "omahabeach_warfare_night",
    queryName: "Omaha_N",
    prettyName: "OMAHA BEACH Warfare",
    base: "Omaha Beach",
    gamemode: "Warfare",
    environment: "Dusk",
    attackers: "",
    image: "OmahaBeach",
  },
  {
    mapName: "PHL_L_1944_OffensiveGER",
    queryName: "PHL",
    prettyName: "PURPLE HEART LANE Offensive",
    base: "Purple Heart Lane",
    gamemode: "Offensive",
    environment: "Day",
    attackers: "GER",
    image: "PurpleHeartLane",
  },
  {
    mapName: "PHL_L_1944_OffensiveUS",
    queryName: "PHL",
    prettyName: "PURPLE HEART LANE Offensive",
    base: "Purple Heart Lane",
    gamemode: "Offensive",
    environment: "Day",
    attackers: "US",
    image: "PurpleHeartLane",
  },
  {
    mapName: "PHL_L_1944_Warfare",
    queryName: "PHL",
    prettyName: "PURPLE HEART LANE Warfare",
    base: "Purple Heart Lane",
    gamemode: "Warfare",
    environment: "Rain",
    attackers: "",
    image: "PurpleHeartLane",
  },
  {
    mapName: "PHL_L_1944_Warfare_Night",
    queryName: "PHL_N",
    prettyName: "PURPLE HEART LANE Warfare",
    base: "Purple Heart Lane",
    gamemode: "Warfare",
    environment: "Night",
    attackers: "",
    image: "PurpleHeartLane",
  },
  {
    mapName: "PHL_S_1944_Rain_P_Skirmish",
    queryName: "DEV_K_Rain_SKM",
    prettyName: "PURPLE HEART LANE Skirmish",
    base: "Purple Heart Lane",
    gamemode: "Skirmish",
    environment: "Rain",
    attackers: "",
    image: "PurpleHeartLane",
  },
  {
    mapName: "PHL_S_1944_Morning_P_Skirmish",
    queryName: "DEV_K_Morning_SKM",
    prettyName: "PURPLE HEART LANE Skirmish",
    base: "Purple Heart Lane",
    gamemode: "Skirmish",
    environment: "Morning",
    attackers: "",
    image: "PurpleHeartLane",
  },
  {
    mapName: "PHL_S_1944_Night_P_Skirmish",
    queryName: "DEV_K_Night_SKM",
    prettyName: "PURPLE HEART LANE Skirmish",
    base: "Purple Heart Lane",
    gamemode: "Skirmish",
    environment: "Night",
    attackers: "",
    image: "PurpleHeartLane",
  },
  {
    mapName: "remagen_offensive_ger",
    queryName: "Remagen",
    prettyName: "REMAGEN Offensive",
    base: "Remagen",
    gamemode: "Offensive",
    environment: "Foggy",
    attackers: "GER",
    image: "Remagen",
  },
  {
    mapName: "remagen_offensive_us",
    queryName: "Remagen",
    prettyName: "REMAGEN Offensive",
    base: "Remagen",
    gamemode: "Offensive",
    environment: "Day",
    attackers: "US",
    image: "Remagen",
  },
  {
    mapName: "remagen_warfare",
    queryName: "Remagen",
    prettyName: "REMAGEN Warfare",
    base: "Remagen",
    gamemode: "Warfare",
    environment: "Day",
    attackers: "",
    image: "Remagen",
  },
  {
    mapName: "remagen_warfare_night",
    queryName: "Remagen_N",
    prettyName: "REMAGEN Warfare",
    base: "Remagen",
    gamemode: "Warfare",
    environment: "Night",
    attackers: "",
    image: "Remagen",
  },
  {
    mapName: "SMDM_S_1944_Day_P_Skirmish",
    queryName: "DEV_M_SKM",
    prettyName: "ST MARIE DU MONT Skirmish",
    base: "St. Marie Du Mont",
    gamemode: "Skirmish",
    environment: "Day",
    attackers: "",
    image: "Sainte-Marie-du-Mont",
  },
  {
    mapName: "SMDM_S_1944_Rain_P_Skirmish",
    queryName: "DEV_M_Rain_SKM",
    prettyName: "ST MARIE DU MONT Skirmish",
    base: "St. Marie Du Mont",
    gamemode: "Skirmish",
    environment: "Rain",
    attackers: "",
    image: "Sainte-Marie-du-Mont",
  },
  {
    mapName: "SMDM_S_1944_Night_P_Skirmish",
    queryName: "DEV_M_Night_SKM",
    prettyName: "ST MARIE DU MONT Skirmish",
    base: "St. Marie Du Mont",
    gamemode: "Skirmish",
    environment: "Night",
    attackers: "",
    image: "Sainte-Marie-du-Mont",
  },
  {
    mapName: "SME_S_1944_Day_P_Skirmish",
    queryName: "DEV_I_DAY_SKM",
    prettyName: "SAINTE-MÈRE-ÉGLISE Skirmish",
    base: "St. Mere Eglise",
    gamemode: "Warfare",
    environment: "Day",
    attackers: "",
    image: "Sainte-Mère-Église",
  },
  {
    mapName: "SME_S_1944_Morning_P_Skirmish",
    queryName: "DEV_I_MORNING_SKM",
    prettyName: "SAINTE-MÈRE-ÉGLISE Skirmish",
    base: "St. Mere Eglise",
    gamemode: "Warfare",
    environment: "Dawn",
    attackers: "",
    image: "Sainte-Mère-Église",
  },
  {
    mapName: "SME_S_1944_Night_P_Skirmish",
    queryName: "DEV_I_NIGHT_SKM",
    prettyName: "SAINTE-MÈRE-ÉGLISE Skirmish",
    base: "St. Mere Eglise",
    gamemode: "Warfare",
    environment: "Night",
    attackers: "",
    image: "Sainte-Mère-Église",
  },
  {
    mapName: "stalingrad_offensive_ger",
    queryName: "Stalin",
    prettyName: "STALINGRAD Offensive",
    base: "Stalingrad",
    gamemode: "Offensive",
    environment: "Day",
    attackers: "GER",
    image: "Stalingrad",
  },
  {
    mapName: "stalingrad_offensive_rus",
    queryName: "Stalin",
    prettyName: "STALINGRAD Offensive",
    base: "Stalingrad",
    gamemode: "Offensive",
    environment: "Day",
    attackers: "RUS",
    image: "Stalingrad",
  },
  {
    mapName: "stalingrad_warfare",
    queryName: "Stalin",
    prettyName: "STALINGRAD Warfare",
    base: "Stalingrad",
    gamemode: "Warfare",
    environment: "Day",
    attackers: "",
    image: "Stalingrad",
  },
  {
    mapName: "stalingrad_warfare_night",
    queryName: "Stalin_N",
    prettyName: "STALINGRAD Warfare",
    base: "Stalingrad",
    gamemode: "Warfare",
    environment: "Night",
    attackers: "",
    image: "Stalingrad",
  },
  {
    mapName: "stmariedumont_off_ger",
    queryName: "StMarie",
    prettyName: "ST MARIE DU MONT OFF",
    base: "St. Marie Du Mont",
    gamemode: "Offensive",
    environment: "Day",
    attackers: "GER",
    image: "Sainte-Marie-du-Mont",
  },
  {
    mapName: "stmariedumont_off_us",
    queryName: "StMarie",
    prettyName: "ST MARIE DU MONT OFF",
    base: "St. Marie Du Mont",
    gamemode: "Offensive",
    environment: "Day",
    attackers: "US",
    image: "Sainte-Marie-du-Mont",
  },
  {
    mapName: "stmariedumont_warfare",
    queryName: "StMarie",
    prettyName: "ST MARIE DU MONT Warfare",
    base: "St. Marie Du Mont",
    gamemode: "Warfare",
    environment: "Day",
    attackers: "",
    image: "Sainte-Marie-du-Mont",
  },
  {
    mapName: "stmariedumont_warfare_night",
    queryName: "StMarie_N",
    prettyName: "ST MARIE DU MONT Warfare",
    base: "St. Marie Du Mont",
    gamemode: "Warfare",
    environment: "Night",
    attackers: "",
    image: "Sainte-Marie-du-Mont",
  },
  {
    mapName: "stmereeglise_offensive_ger",
    queryName: "SME",
    prettyName: "SAINTE-MÈRE-ÉGLISE Offensive",
    base: "St. Mere Eglise",
    gamemode: "Offensive",
    environment: "Dawn",
    attackers: "GER",
    image: "Sainte-Mère-Église",
  },
  {
    mapName: "stmereeglise_offensive_us",
    queryName: "SME",
    prettyName: "SAINTE-MÈRE-ÉGLISE Offensive",
    base: "St. Mere Eglise",
    gamemode: "Offensive",
    environment: "Day",
    attackers: "US",
    image: "Sainte-Mère-Église",
  },
  {
    mapName: "stmereeglise_warfare",
    queryName: "SME",
    prettyName: "SAINTE-MÈRE-ÉGLISE Warfare",
    base: "St. Mere Eglise",
    gamemode: "Warfare",
    environment: "Day",
    attackers: "",
    image: "Sainte-Mère-Église",
  },
  {
    mapName: "stmereeglise_warfare_night",
    queryName: "SME_N",
    prettyName: "SAINTE-MÈRE-ÉGLISE Warfare",
    base: "St. Mere Eglise",
    gamemode: "Warfare",
    environment: "Night",
    attackers: "",
    image: "Sainte-Mère-Église",
  },
  {
    mapName: "utahbeach_offensive_ger",
    queryName: "Utah",
    prettyName: "UTAH BEACH Offensive",
    base: "Utah Beach",
    gamemode: "Offensive",
    environment: "Day",
    attackers: "GER",
    image: "Utah_Beach",
  },
  {
    mapName: "utahbeach_offensive_us",
    queryName: "Utah",
    prettyName: "UTAH BEACH Offensive",
    base: "Utah Beach",
    gamemode: "Offensive",
    environment: "Day",
    attackers: "US",
    image: "Utah_Beach",
  },
  {
    mapName: "utahbeach_warfare",
    queryName: "Utah",
    prettyName: "UTAH BEACH Warfare",
    base: "Utah Beach",
    gamemode: "Warfare",
    environment: "Day",
    attackers: "",
    image: "Utah_Beach",
  },
  {
    mapName: "utahbeach_warfare_night",
    queryName: "Utah_N",
    prettyName: "UTAH BEACH Warfare",
    base: "Utah Beach",
    gamemode: "Warfare",
    environment: "Night",
    attackers: "",
    image: "Utah_Beach",
  },
];
