export const platformGames = {
  pc: ["bf3", "bf4", "bfh", "bf1", "bfv", "bf2042"],
  xboxone: ["bf4", "bfh", "bf1", "bfv", "bf2042"],
  xbox360: ["bf3", "bf4", "bfh"],
  ps4: ["bf4", "bfh", "bf1", "bfv", "bf2042"],
  ps3: ["bf3", "bf4", "bfh"],
  ps5: ["bf2042"],
  xboxseries: ["bf2042"],
};

export const differentWidth = {
  bfh: "380px",
  bf2042: "320px",
};

export const bflistGames = [
  "bf2",
  "bfbc2",
  "bf2142",
  "bfvietnam",
  "bf1942",
  "bf3",
  "bf4",
  "bfh",
];
export const frostbite3 = ["bf4", "bf1", "bfv"];

export const platformImage = {
  pc: "pc",
  xboxone: "xbox",
  xbox360: "xbox",
  ps4: "psn",
  ps3: "psn",
};
export const shortName = {
  bf3: "3",
  bf4: "4",
  bfh: "HARDLINE",
  bf1: "1",
  bfv: "5",
  bf2042: "2042",
};

export const gameStats = {
  bf3: {
    killsPerMinute: "killsPerMinute",
    scorePerMinute: "scorePerMinute",
    skill: "skill",
    killDeath: "killDeath",
    longestHeadShot: "longestHeadShot",
    winPercent: "winPercent",
    headshotPercent: "headshots",
    accuracy: "accuracy",
    bestClass: "bestClass",
    highestKillStreak: "highestKillStreak",
    revives: "revives",
    repairs: "repairs",
    resupplies: "resupplies",
    timePlayed: "timePlayed",
  },
  bf4: {
    killsPerMinute: "killsPerMinute",
    scorePerMinute: "scorePerMinute",
    skill: "skill",
    killDeath: "killDeath",
    longestHeadShot: "longestHeadShot",
    winPercent: "winPercent",
    headshotPercent: "headshots",
    accuracy: "accuracy",
    bestClass: "bestClass",
    highestKillStreak: "highestKillStreak",
    revives: "revives",
    infantryKillDeath: "infantryKillDeath",
    infantryKillsPerMinute: "infantryKillsPerMinute",
    timePlayed: "timePlayed",
  },
  bfh: {
    killsPerMinute: "killsPerMinute",
    scorePerMinute: "scorePerMinute",
    winPercent: "winPercent",
    killDeath: "killDeath",
    accuracy: "accuracy",
    enforcer: "enforcer",
    mechanic: "mechanic",
    operator: "operator",
    professional: "professional",
    hacker: "hacker",
    bestClass: "bestClass",
    cashPerMinute: "cashPerMinute",
    killAssists: "killAssists",
    timePlayed: "timePlayed",
  },
  bf1: {
    killsPerMinute: "killsPerMinute",
    scorePerMinute: "scorePerMinute",
    skill: "skill",
    killDeath: "killDeath",
    longestHeadShot: "longestHeadShot",
    winPercent: "winPercent",
    headshotPercent: "headshots",
    accuracy: "accuracy",
    bestClass: "bestClass",
    highestKillStreak: "highestKillStreak",
    revives: "revives",
    infantryKillDeath: "infantryKillDeath",
    infantryKillsPerMinute: "infantryKillsPerMinute",
    timePlayed: "timePlayed",
  },
  bfv: {
    killsPerMinute: "killsPerMinute",
    scorePerMinute: "scorePerMinute",
    saviorKills: "saviorKills",
    killDeath: "killDeath",
    longestHeadShot: "longestHeadShot",
    winPercent: "winPercent",
    headshotPercent: "headshots",
    accuracy: "accuracy",
    bestClass: "bestClass",
    highestKillStreak: "highestKillStreak",
    revives: "revives",
    infantryKillDeath: "infantryKillDeath",
    infantryKillsPerMinute: "infantryKillsPerMinute",
    timePlayed: "timePlayed",
  },
  bf2042: {
    killsPerMinute: "killsPerMinute",
    damagePerMinute: "damagePerMinute",
    headshotPercent: "headshots",
    killDeath: "killDeath",
    matchesPlayed: "matchesPlayed",
    winPercent: "winPercent",
    killsPerMatch: "killsPerMatch",
    damagePerMatch: "damagePerMatch",
    bestClass: "bestClass",
    objectiveTime: "objective.time",
    kills: "kills",
    meleeKills: "dividedKills.melee",
    vehicleKills: "dividedKills.vehicle",
    timePlayed: "timePlayed",
  },
};
